name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust to the version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload code to PythonAnywhere
        run: |
          zip -r app.zip *  # Create a zip of your app
          curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/files/path/home/${{ secrets.PA_USERNAME }}/app.zip \
          --data-binary @app.zip \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"
          
      - name: Reload PythonAnywhere Web App
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/YOUR_WEB_APP_DOMAIN/reload/ \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"
